#!/bin/bash
#SBATCH --job-name=genomic_data
#SBATCH --partition=128×24
#SBATCH --mail-type=ALL
#SBATCH --mail-user=igpedraz@ucsc.edu
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --output=genomic_data.out 
#SBATCH --mem=250M

## Run this script to download the genomic data for each hibernating species
## species_gcf.txt contains the name of species and GCF number which this script will pull from.

cd /hb/groups/kelley_training/itzel/data/genomic

module load miniconda3

source activate /hb/home/igpedraz/.conda/envs/ncbi_datasets

while read line; do
    sp=$(echo ${line} | awk '{ print $1; }')
    gcf=$(echo ${line} | awk '{ print $2; }')
    echo "*** downloading genomic data for ${sp}, accession ${gcf} ***"
    datasets download genome accession ${gcf} --include genome,protein,gff3,rna,cds --filename ${sp}.zip
    unzip ${sp}.zip
    mkdir -p ${sp}
    cp ncbi_dataset/data/${gcf}/* ${sp}
    rm -r ncbi_dataset
    rm README.md
done < species_gcf.txt

rm *.zip

conda deactivate
